apiVersion: v1
kind: Service
metadata:
  name: kubernetes-node-server-replicaset-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    nodePort: 30036
    port: 80
    targetPort: 5000
  selector:
    tier: frontend
